hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  gen_batch_size: ${data.train_batch_size}

algorithm:
  adv_estimator: grpo
  norm_adv_by_std_in_grpo: True
  use_kl_in_reward: False
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

reward:
  num_workers: 1
  reward_manager:
    name: naive
  custom_reward_function:
    path: null
    name: compute_score
    reward_kwargs:
      unconditional_lambda: 0.1
      clip_reward: true
      positive_improvement_only: true
      hint_template_path: null
      reward_model_name: null
  reward_model:
    enable: true
    enable_resource_pool: false
    n_gpus_per_node: 1
    nnodes: 1
    model_path: null
    rollout:
      name: vllm
      dtype: bfloat16
      gpu_memory_utilization: 0.2
      tensor_model_parallel_size: 1
      max_num_batched_tokens: 4096
      max_model_len: 4096
      free_cache_engine: true
      skip_tokenizer_init: false
      prompt_length: 4096
      response_length: 1

trainer:
  project_name: ppl-rl-verl
  experiment_name: qwen3_1.7b_ppl_rl
