#!/bin/bash
set -eu

export CUDA_VISIBLE_DEVICES=0,1
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
export TOKENIZERS_PARALLELISM=false
export HYDRA_FULL_ERROR=1
export CUDA_LAUNCH_BLOCKING=1

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=/scratch/rst306/action_abstractions/action_abstraction/verl_data/sft_dataset_no_rl_partial_05_less1_traintest/train.parquet \
    data.val_files=/scratch/rst306/action_abstractions/action_abstraction/verl_data/sft_dataset_no_rl_partial_05_less1_traintest/test.parquet \
    data.train_batch_size=128 \
    data.val_batch_size=32 \
    data.max_prompt_length=3420 \
    data.max_response_length=8192 \
    actor_rollout_ref.model.path=Qwen/Qwen3-1.7B \
    actor_rollout_ref.model.lora_adapter_path=/scratch/rst306/action_abstractions/action_abstraction/sft_models/solver/Qwen3_1_7B-solver/checkpoint-3400 \
    actor_rollout_ref.model.lora_rank=4 \
    actor_rollout_ref.model.lora_alpha=8 \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.model.target_modules=['q_proj','k_proj','v_proj','o_proj','up_proj','gate_proj','down_proj'] \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.use_liger=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=24576 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    +actor_rollout_ref.actor.fsdp_config.grad_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.dtype=bfloat16 \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.45 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.rollout_data_dir=/scratch/rst306/action_abstractions/action_abstraction/verl_outputs \
    trainer.project_name='verl_deepscaler_easy' \
    trainer.experiment_name='verl_deepscaler_easy_1.7B_2xa100_sftlora' \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=50 \
    trainer.total_epochs=4 \
    reward.custom_reward_function.path=/scratch/rst306/action_abstractions/action_abstraction/verl/verl/utils/reward_score/deepscaler_math_reward.py \
    reward.custom_reward_function.name=compute_score \
    reward.reward_manager.name=naive \
    ray_kwargs.ray_init.num_cpus=8 \
    trainer.default_local_dir=/scratch/rst306/action_abstractions/action_abstraction/verl_checkpoints \
    "$@"