#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Reward-probe defaults: skip pre-train validation, keep the training batch
# small, and push eval/save far enough out that they should not trigger during
# a short exploratory run.
export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
export ABSTRACTION_MAX_RESP_LEN=${ABSTRACTION_MAX_RESP_LEN:-800}
export TRAINER_VAL_BEFORE_TRAIN=${TRAINER_VAL_BEFORE_TRAIN:-False}
export TRAINER_SAVE_FREQ=${TRAINER_SAVE_FREQ:-999999999}
export TRAINER_TEST_FREQ=${TRAINER_TEST_FREQ:-999999999}
export TRAINER_EXPERIMENT_NAME=${TRAINER_EXPERIMENT_NAME:-qwen06b_gsm8k_two_policy_decoupled_reward_probe}
export RUN_TAG=${RUN_TAG:-decoupled_reward_probe_$(date -u +%Y%m%d_%H%M%S)}

# Alternate update steps across the two branches.
export DECOUPLED_SOLVER_SCHEDULE_ENABLE=${DECOUPLED_SOLVER_SCHEDULE_ENABLE:-True}
export SOLVER_UPDATE_EVERY_N_STEPS=${SOLVER_UPDATE_EVERY_N_STEPS:-2}
export NON_UPDATE_SOLVER_ROLLOUTS=${NON_UPDATE_SOLVER_ROLLOUTS:-1}
export NON_UPDATE_SOLVER_TEMPERATURE=${NON_UPDATE_SOLVER_TEMPERATURE:-0.0}
export NON_UPDATE_SOLVER_TOP_P=${NON_UPDATE_SOLVER_TOP_P:-1.0}
export NON_UPDATE_SOLVER_TOP_K=${NON_UPDATE_SOLVER_TOP_K:--1}

export DECOUPLED_ABSTRACTION_SCHEDULE_ENABLE=${DECOUPLED_ABSTRACTION_SCHEDULE_ENABLE:-True}
export ABSTRACTION_USE_SOLVER_STEP_COMPLEMENT=${ABSTRACTION_USE_SOLVER_STEP_COMPLEMENT:-True}
export NON_UPDATE_ABSTRACTIONS=${NON_UPDATE_ABSTRACTIONS:-1}
export NON_UPDATE_ABSTRACTION_TEMPERATURE=${NON_UPDATE_ABSTRACTION_TEMPERATURE:-0.0}
export NON_UPDATE_ABSTRACTION_TOP_P=${NON_UPDATE_ABSTRACTION_TOP_P:-1.0}
export NON_UPDATE_ABSTRACTION_TOP_K=${NON_UPDATE_ABSTRACTION_TOP_K:--1}
export TWO_POLICY_FILTER_SOLVER_GROUPS=${TWO_POLICY_FILTER_SOLVER_GROUPS:-False}
export TWO_POLICY_REQUIRE_PRINCIPLE_HEADERS=${TWO_POLICY_REQUIRE_PRINCIPLE_HEADERS:-False}

exec "${SCRIPT_DIR}/run_qwen_two_policy_gsm8k_qwen06b_explicit.sh" "$@"
